### ISSUE TITLE
Helping merchant to fix problem with automatic invoices and order confirmations

### ISSUE THREAD

**Issue by sereshqua** [emspay/magento1#6]

**Comment by sereshqua** [comment]
Dave, please invite Satya <satya@taurosmedia.com> to this repo

**Comment by sereshqua** [comment]
FYI @dligthart

**Comment by ghost** [comment]
Today I have checked the shop: https://nnstoffen.nl/ which has problems with EMS_Pay module to work. I was communicating with Satya while doing this.

**Here is the result:**
- access.log, error.log files had 5GB each. It's a problem because opening so big files can generate unexpected problems for the server.
- TIG_PostNL module throws a lot of Exceptions in magento/var/log/TIG_PostNL/TIG_PostNL_Exception.log
- in php.log I've found Fatal Error thrown, made by TIG_PostNL module

In this situation EMS_Pay module had error as well, but very weird one that was made by IndexController::ipnAction() call which is callback function called by EMS server. The error says "Invalid method Mage_Sales_Model_Order::queueNewOrderEmail(...)". The object $order is probably empty because of previous fatal errors when EMS server is doing callback call to Magento - but this has to be checked and verified. 

Because of critical errors present in the shop I suggested to turn off TIG_PostNL module, eliminate critical errors and then check EMS_Pay if works without the error - on Test version.

Satya mentioned that other payment modules did work well with TIG_PostNL module which is interesting as well.

Further investigation is needed on Test version. Satya is making this can happen.

**Comment by ghost** [comment]
**Update**:
I've examined _Customweb_EMSeCommerceCw_ module. The reason why it works and EMS_Pay does not - is completely different communication method like I assumed. _Customweb_EMSeCommerceCw_ is using _Magento's SOAP API_ and iframe. No other modules run through _Magento Core_ when communication payment is being established between shop and server. So probably (coz I didn't test it, I couldn't on Live to do so) problematic _TIG_ shipping module is not being fired at all when Payment operations are done. It explains a lot. 

_EMS_Pay_ is not developed in the best way. Making it work through SOAP makes things much more complicated and I'm not able to estimate needed time to accomplish the task. Time estimation depends roughly on EMS cooperation with setting up SOAP communication. If you examine _Customweb_EMSeCommerceCw_ module you can see how much work would be needed to make _EMS_Pay_ work as expected even in bad working shops full of Exceptions thrown. I think time spend on changing EMS_Pay module will be counted in weeks.
Let me know about the strategy. I think I investigated everything needed to make final decision - are we going to change EMS_Pay module - a big one, or not.
